import './globals.css'
import { Assistant } from 'next/font/google'

const assistant = Assistant({ weight:"variable", subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={assistant.className + " h-full"}>{children}</body>
    </html>
  )
}
